const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const REFETCH_DATA = "REFETCH_DATA";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const TYPING_START = "TYPING_START";
const TYPING_STOP = "TYPING_STOP";
const ONLINE_USERS = "ONLINE_USERS";
const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVE = "CHAT_LEAVE";
const REFRESH_CHAT = "REFRESH_CHAT";
export {
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  REFETCH_DATA,
  NEW_REQUEST,
  NEW_MESSAGE,
  TYPING_START,
  TYPING_STOP,
  ONLINE_USERS,
  CHAT_JOINED,
  CHAT_LEAVE,
  REFRESH_CHAT,
};
